= ISEC3004 assignment

In this assignment you will make 30 minutes recorded presentation on a security bug. 
You will show what the security bug is, how
to detect and finally how to mitigate it.

== Submission

. Slides: You will make slides for your presentation.
. Demo program: You will develop a program to support your presentation.
. Recording: You will record your presentation in a video file. In your presentation, you talk through your slides and demo how to detect, exploit and patch the security bug.

== Recording

Your recording should include both your audio and camera feed.

Login to https://echo360.org.au/ with your student email to record
your presentation or upload your presentation video file.

Once you finish recording share your presentation, 
with the unit instructor.
You will need to do the following:

. Click to view the recording in Echo360.
. Click on "Share" button below the video playback.
. Under 'Individual', 'Share with:', enter the unit instructor email and press 'Done'.

[NOTE]
--
. OBS Studio is a good tool to record your 
presentation offline. 
. You can find unit instructor email in BB, Contacts.
--

== Slides

Your slides must, at least, include the following
sections. You can include additional sections.

. Title: Vulnerability, your names, and link to the demo program repository
. Background: Background knowledge necessary to understand
the vulnerability. For example if your topic is DOM-based XSS
you should explain Document Object Model and
how JavaScript libraries can use it, what are Events, etc.
. Vulnerability definition: describe the vulnerability,
describe the issue and provide a simple example with a pseudo/real code
. Impact: Describe possible impacts of the vulnerability
. Real-world incident: Describe a real-world incident of 
the vulnerability being exploited in the wild.
. Detection: Describe how to detect the vulnerability
through static analysis (code review) and run-time analysis
. Prevention: Describe multiple ways to patch the vulnerability
and include pros and cons of each patch.
. Conclusion
. References

== Demo program

The demo program should contain the vulnerability that your group has chosen
to demonstrate. You should write tests that cover all the functionality within
your program (these tests are later used to verify that the patched version
hasn't lost any functionality).

You should create a patch branch in this repository.
The patch branch should contain a patched version of 
your program. 

Along with your demo program, you should provide a proof of concept to
demonstrate the vulnerability. This can be done in one of two ways:

. Unit/Integration test: If you are able to write a test (unit test or integration test) that shows
the security bug and later it fails. The test fails because the program is vulnerable.
Your patched program will pass this test. 
. External tool: Write a step-by-step shows 
how the vulnerability could be triggered and exploited. Include this guide
in the `readme`

Use this repository as a template for your demo
program. `Fork`, and `clone` this repository.
Look inside each directory for a sample file
or a guide.

[NOTE]
--
. Flask and JavaScript are used as examples. You are free to choose
any programming language or framework to make your program.
. The patched program should pass all 
your tests.
. Use `DockerFile` and `MakeFile` to make your program portable and easy to
run.
--

== Submission checklist

* [ ] Reviewed the assignment Rubrics in BB.
* [ ] Demo program repository is linked in the presentation.
* [ ] Tests cover program functionality tests.
* [ ] A patched version of the program is created in the patch branch.
* [ ] The patched program passes all tests.
* [ ] `Readme` is updated with program description, how to run the program, how to detect, exploit and patch the bug.
* [ ] Unnecessary template files and guides are removed.
* [ ] Presentation is submitted to BB.
* [ ] Presentation video recording is shared with the unit instructor.

== License

See link:LICENSE[]
