= ISEC3004 assignment

In this assignment you will make 30 minutes recorded presentation on a security bug. 
You will show what the security bug is, how
to detect and finally how to mitigate it.

== Submission

. Slides: You will make slides for your presentation.
. Demo program: You will develop a program to support your presentation.
. Recording: You will record your presentation in a video file. In your presentation, you talk through your slides and demo how to detect, exploit and patch the security bug.

== Recording

Your recording should include both your audio and camera feed.

Use https://echo360.org.au/ to record
your presentation or upload your presentation video file.

In order to share your presentation, you will need to do the following:

. Click to actually view the recording in Echo360.
. Once the video page opens up, click the "Share" button on the bottom of the video.
. You should be able to share it to an individual, so just share it with Pedram. (`Pedram.Hayati@curtin.edu.au`).

[NOTE]
--
OBS Studio is a good tool to record your 
presentation offline. 
--

== Slides

Your slides must, at least, include the following
sections. You can include additional sections.

. Title: Vulnerability, your names, and link to the demo program repository
. Background: Background knowledge necessary to understand
the vulnerability. For example if your topic is DOM-based XSS
you should explain Document Object Model and
how JavaScript libraries can use it, what are Events, etc.
. Vulnerability definition: describe the vulnerability,
describe the issue and provide a simple example with a pseudo/real code
. Impact: Describe possible impacts of the vulnerability
. Real-world incident: Describe a real-world incident of 
the vulnerability being exploited in the wild.
. Detection: Describe how to detect the vulnerability
through static analysis (code review) and run-time analysis
. Prevention: Describe multiple ways to patch the vulnerability
and include pros and cons of each patch.
. Conclusion
. References

== Demo program

The demo program should contain the vulnerability that your group has chosen
to demonstrate. You should write tests that cover all the functionality within
your program (these tests are later used to verify that the patched version
hasn't lost any functionality).

Along with your demo program, you should provide a proof of concept to
demonstrate the vulnerability. This can be done in one of two ways:

. If you are able to write a test case as a proof of concept, then feel free
to do that.
** You are allowed to use any method to demonstrate this. 
. For more complex proof of concepts, feel free to write a guide that walks
through how the vulnerability could be triggered. You are allowed to use
and talk about any external tools you may make use of.

Use this repository as a template for your demo
program. `Fork`, and `clone` this repository.
Look inside each directory for a sample file
or a guide.

You should create a patch branch in this repository.
The patch branch should contain a patched version of 
your program. 

[NOTE]
--
The sample files use Flask as an example as that is what you're accustomed to from your labs. Feel free to write your program in anything.
--

[NOTE]
--
The patched program should pass all 
your tests.
--

== Submission checklist

* [ ] Reviewed the assignment Rubrics in BB.
* [ ] Demo program repository is linked in the presentation.
* [ ] Tests cover program functionality and security bug.
* [ ] A patched version of the program is created in the patch branch.
* [ ] The patched program passes all tests.
* [ ] `Readme` is updated with program description, how to run the program, how to detect, exploit and patch the bug.
* [ ] Unnecessary template files and guides are removed.
* [ ] Presentation is submitted to BB.
* [ ] Presentation video recording is shared with the unit instructor.

== License

See link:LICENSE[]
